# Generated by Django 5.0.3 on 2024-04-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingwebsite.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingwebsite.election')),
            ],
        ),
    ]
